version: '3.1'

services:
  php-apache:
      image: php:7.4-apache
      container_name: my-php-apache-container
      restart: always
      volumes:
        - ./:/var/www/html
      ports:
        - "8080:80"
  db:
    image: mysql:latest
    container_name: my-mysql-container
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"